name: 'yii2-options'

services:
  postgres:
    container_name: yii2-options-postgres
    image: postgres:13.6
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: yii2-options-tests
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
      - ./docker/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./docker/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

# Networks Setup
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/28